/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpotlightRouteImport } from './routes/spotlight'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ForPartnersRouteImport } from './routes/for-partners'
import { Route as ForCreativesRouteImport } from './routes/for-creatives'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceSlugRouteImport } from './routes/marketplace.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminDesignersRouteImport } from './routes/_authenticated/admin.designers'
import { Route as AuthenticatedAdminContactRouteImport } from './routes/_authenticated/admin.contact'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated/admin.applications'

const SpotlightRoute = SpotlightRouteImport.update({
  id: '/spotlight',
  path: '/spotlight',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPartnersRoute = ForPartnersRouteImport.update({
  id: '/for-partners',
  path: '/for-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCreativesRoute = ForCreativesRouteImport.update({
  id: '/for-creatives',
  path: '/for-creatives',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSlugRoute = MarketplaceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketplaceRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/admin/partners',
    path: '/admin/partners',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDesignersRoute =
  AuthenticatedAdminDesignersRouteImport.update({
    id: '/admin/designers',
    path: '/admin/designers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminContactRoute =
  AuthenticatedAdminContactRouteImport.update({
    id: '/admin/contact',
    path: '/admin/contact',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/admin/applications',
    path: '/admin/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/for-creatives': typeof ForCreativesRoute
  '/for-partners': typeof ForPartnersRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/spotlight': typeof SpotlightRoute
  '/admin/login': typeof AdminLoginRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/designers': typeof AuthenticatedAdminDesignersRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/for-creatives': typeof ForCreativesRoute
  '/for-partners': typeof ForPartnersRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/spotlight': typeof SpotlightRoute
  '/admin/login': typeof AdminLoginRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/designers': typeof AuthenticatedAdminDesignersRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/for-creatives': typeof ForCreativesRoute
  '/for-partners': typeof ForPartnersRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/spotlight': typeof SpotlightRoute
  '/admin/login': typeof AdminLoginRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/contact': typeof AuthenticatedAdminContactRoute
  '/_authenticated/admin/designers': typeof AuthenticatedAdminDesignersRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/for-creatives'
    | '/for-partners'
    | '/marketplace'
    | '/spotlight'
    | '/admin/login'
    | '/marketplace/$slug'
    | '/admin/applications'
    | '/admin/contact'
    | '/admin/designers'
    | '/admin/partners'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/for-creatives'
    | '/for-partners'
    | '/marketplace'
    | '/spotlight'
    | '/admin/login'
    | '/marketplace/$slug'
    | '/admin/applications'
    | '/admin/contact'
    | '/admin/designers'
    | '/admin/partners'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/for-creatives'
    | '/for-partners'
    | '/marketplace'
    | '/spotlight'
    | '/admin/login'
    | '/marketplace/$slug'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/contact'
    | '/_authenticated/admin/designers'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ForCreativesRoute: typeof ForCreativesRoute
  ForPartnersRoute: typeof ForPartnersRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  SpotlightRoute: typeof SpotlightRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spotlight': {
      id: '/spotlight'
      path: '/spotlight'
      fullPath: '/spotlight'
      preLoaderRoute: typeof SpotlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-partners': {
      id: '/for-partners'
      path: '/for-partners'
      fullPath: '/for-partners'
      preLoaderRoute: typeof ForPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-creatives': {
      id: '/for-creatives'
      path: '/for-creatives'
      fullPath: '/for-creatives'
      preLoaderRoute: typeof ForCreativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$slug': {
      id: '/marketplace/$slug'
      path: '/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof MarketplaceSlugRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/designers': {
      id: '/_authenticated/admin/designers'
      path: '/admin/designers'
      fullPath: '/admin/designers'
      preLoaderRoute: typeof AuthenticatedAdminDesignersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/contact': {
      id: '/_authenticated/admin/contact'
      path: '/admin/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AuthenticatedAdminContactRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminContactRoute: typeof AuthenticatedAdminContactRoute
  AuthenticatedAdminDesignersRoute: typeof AuthenticatedAdminDesignersRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminContactRoute: AuthenticatedAdminContactRoute,
  AuthenticatedAdminDesignersRoute: AuthenticatedAdminDesignersRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceSlugRoute: typeof MarketplaceSlugRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceSlugRoute: MarketplaceSlugRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ForCreativesRoute: ForCreativesRoute,
  ForPartnersRoute: ForPartnersRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  SpotlightRoute: SpotlightRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
